language: cpp  # Travis-CI does not currently support Python and Mac OS X

os:
  - linux
  - osx

env:
  - PYTHON_VERSION=3.8
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - env: PYTHON_VERSION=3.7

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set notify_outdated_conda false
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$PYTHON_VERSION
  - conda activate test-environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda install appdirs bidict cartopy gdal matplotlib numpy psutil pyproj PySide2;
    else
      conda install appdirs bidict cartopy gdal matplotlib numpy psutil pyproj PySide2;
      export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib:$LD_LIBRARY_PATH;
    fi
  - pip install coveralls
  # no-deps because coonda's PySide2 is not detected
  - pip install --no-deps .
  - conda list --show-channel-urls

script:
  - coverage run --source hyo2 setup.py test

after_success:
  - coveralls
